icon/button and link directed to officer list
Aggie-Web-Developers/awd-website pull request #234
Opened 2021-07-08 01:18 UTC by tonyy007

#### Category
- [ ] Bug Fix
- [x] New Feature
- [ ] Hotfix

#### Related issues:

- mentioned in #183 

#### What does this PR do?

We added a page to list the officers. In addition, we added a icon/button on the officer's portal page to redirect to this page.

#### Notes for Reviewer (@cdconn00)

2021-07-08 15:32 UTC, cdconn00 requested changes
Tony great work,

Couple of small things to cleanup then we're ready to merge this:

1. On the homescreen (where you see all the purple buttons) change the div element with a class of row that contains that contains the officer button to be 'justify-content-center' instead of 'justify-content between', it should look like the image below when done.
2. Add a newline to the end of officers/index.ejs, everyfile should end with a newline.

Good work.

![Screenshot_2](https://user-images.githubusercontent.com/30357632/124950125-c28e4b00-dfd7-11eb-9fff-241782795991.png)

2021-07-08 19:37 UTC, tonyy007 commented
Complete.

2021-07-09 12:36 UTC, cdconn00 approved these changes

2021-07-09 12:36 UTC, merged

2021-07-09 12:36 UTC, cdconn00 commented
Merged, good work